Update action.yml

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -20,18 +20,32 @@ jobs:
       - uses: actions/checkout@v3
       - id: readid
         run: |
-           aws s3 cp s3://awsinstanceid/InstanceID.txt ${{github.workspace}}/InstanceID1.txt
-           input='${{github.workspace}}/InstanceID1.txt'
-           while IFS= read -r line
-           do
-             echo "$line"
-             status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
-             if [ "$status" != "running" ];then
-               aws ec2 start-instances --instance-ids $line
-               echo "::set-output name=runner::$line"
-               echo "::set-output name=flag::true"
-               break
-             fi
-             echo "::set-output name=flag::false"
-           done < "$input"
-           sleep 60
+            retry=0
+            maxRetries=5
+            retryInterval=60
+            n=0
+            until [[ ${retry} -ge ${maxRetries} || $n -gt 0 ]]
+            do
+             aws s3 cp s3://awsinstanceid/Instanceidawsv1.txt ${{ github.workspace }}/id.txt
+             input='${{ github.workspace }}/id.txt'
+             sed 's/\r$//' ${{ github.workspace }}/id.txt > input.txt
+             echo "" >> input.txt
+             while IFS="\n" read -r line
+             do
+               echo "$line"
+               status=$(aws ec2 describe-instance-status --instance-ids $line --include-all-instances | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
+               if [ "$status" == "stopped" ];then
+                 aws ec2 start-instances --instance-ids $line
+                 echo "::set-output name=runner::$line"
+                 n=1
+                 break               
+               fi
+              done < "$input"
+            retry=$[${retry}+1]
+            echo "Retrying [${retry}/${maxRetries}] in ${retryInterval}(s) "
+            sleep ${retryInterval}
+            done
+            if [ ${retry} -ge ${maxRetries} ]; then
+              echo "Failed after ${maxRetries} attempts!"
+              exit 1
+            fi                    
