Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -15,60 +15,73 @@ jobs:
         continue-on-error: true
       - id: readid
         run: |
-           aws s3 cp s3://awsinstanceid/ec2IDaws.txt ${{ github.workspace }}/instanceid.txt
-           input='${{ github.workspace }}/instanceid.txt'
-           sed 's/\r$//' ${{ github.workspace }}/instanceid.txt > input.txt
-           echo "" >> input.txt
-           while IFS="\n" read -r line
-           do
-             echo "$line"
-             status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
-             if [ "$status" != "running" ];then
-               aws ec2 start-instances --instance-ids $line
-               echo "::set-output name=runner::$line"
-               break
-             fi
-           done < "$input"
+            retry=0
+            maxRetries=5
+            retryInterval=15
+            until [ ${retry} -ge ${maxRetries} ]
+            do
+             aws s3 cp s3://awsinstanceid/ec2IDaws.txt ${{ github.workspace }}/instanceid.txt
+             input='${{ github.workspace }}/instanceid.txt'
+             sed 's/\r$//' ${{ github.workspace }}/instanceid.txt > input.txt
+             echo "" >> input.txt
+             while IFS="\n" read -r line
+             do
+               echo "$line"
+               status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
+               if [ "$status" != "running" ];then
+                 aws ec2 start-instances --instance-ids $line
+                 echo "::set-output name=runner::$line"
+                 break
+               fi
+              done < "$input"
+            retry=$[${retry}+1]
+            echo "Retrying [${retry}/${maxRetries}] in ${retryInterval}(s) "
+            sleep ${retryInterval}
+            done
+            if [ ${retry} -ge ${maxRetries} ]; then
+             echo "Failed after ${maxRetries} attempts!"
+             exit 1
+            fi
            
-        name: Retrying
-        continue-on-error: true
-      - id: retry1
-        if: steps.startrunner.output=='failure'        
-        run: |
-           aws s3 cp s3://awsinstanceid/InstanceID.txt ${{github.workspace}}/InstanceID1.txt
-           input='${{github.workspace}}/InstanceID1.txt'
-           while IFS= read -r line
-           do
-             echo "$line"
-             status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
-             if [ "$status" != "running" ];then
-               aws ec2 start-instances --instance-ids $line
-               echo "::set-output name=runner::$line"
-               break
-             fi
-           done < "$input"
-           sleep 60
-           exit 1
+#         name: Retrying
+#         continue-on-error: true
+#       - id: retry1
+#         if: steps.startrunner.output=='failure'        
+#         run: |
+#            aws s3 cp s3://awsinstanceid/InstanceID.txt ${{github.workspace}}/InstanceID1.txt
+#            input='${{github.workspace}}/InstanceID1.txt'
+#            while IFS= read -r line
+#            do
+#              echo "$line"
+#              status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
+#              if [ "$status" != "running" ];then
+#                aws ec2 start-instances --instance-ids $line
+#                echo "::set-output name=runner::$line"
+#                break
+#              fi
+#            done < "$input"
+#            sleep 60
+#            exit 1
              
-        name: Retrying again
-        continue-on-error: true
-      - id: retry2
-        if: steps.startrunner.output=='failure'        
-        run: |
-           aws s3 cp s3://awsinstanceid/InstanceID.txt ${{github.workspace}}/InstanceID1.txt
-           input='${{github.workspace}}/InstanceID1.txt'
-           while IFS= read -r line
-           do
-             echo "$line"
-             status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
-             if [ "$status" != "running" ];then
-               aws ec2 start-instances --instance-ids $line
-               echo "::set-output name=runner::$line"
-               break
-             fi
-           done < "$input"
-           sleep 60
-           exit 1
+#         name: Retrying again
+#         continue-on-error: true
+#       - id: retry2
+#         if: steps.startrunner.output=='failure'        
+#         run: |
+#            aws s3 cp s3://awsinstanceid/InstanceID.txt ${{github.workspace}}/InstanceID1.txt
+#            input='${{github.workspace}}/InstanceID1.txt'
+#            while IFS= read -r line
+#            do
+#              echo "$line"
+#              status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
+#              if [ "$status" != "running" ];then
+#                aws ec2 start-instances --instance-ids $line
+#                echo "::set-output name=runner::$line"
+#                break
+#              fi
+#            done < "$input"
+#            sleep 60
+#            exit 1
     
   build:
      needs: startrunner
